'use client';

import { useEffect, useState, useRef, type ReactNode } from 'react';

function cn(...inputs: (string | false | null | undefined)[]): string {
  return inputs.filter(Boolean).join(' ');
}

function useIsVisible(ref: React.RefObject<HTMLElement | null>) {
  const [visible, setVisible] = useState(false);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const obs = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setVisible(true);
          obs.disconnect();
        }
      },
      { threshold: 0.2 },
    );
    obs.observe(el);
    return () => obs.disconnect();
  }, [ref]);
  return visible;
}

export function AnimatedTerminal({ className }: { className?: string }) {
  const ref = useRef<HTMLDivElement>(null);
  const visible = useIsVisible(ref);

  const lines = [
    '$ cargo install sylc',
    '    Updating crates.io index',
    '  Downloading sylc v0.1.0',
    '  Installing sylc v0.1.0',
    '   Compiling sylc v0.1.0',
    '    Finished installing sylc v0.1.0',
    '$ sylc counter.syl',
    '// Generated by sylc.',
    '',
    'module Counter(',
    '    input  wire         clk,',
    '    input  wire         rst,',
    '    input  wire         enable,',
    '    output wire [15:0]  value',
    ');',
  ];

  const [revealed, setRevealed] = useState(0);

  useEffect(() => {
    if (!visible) return;
    setRevealed(0);
    let i = 0;
    const timer = setInterval(() => {
      i++;
      setRevealed(i);
      if (i >= lines.length) clearInterval(timer);
    }, 150);
    return () => clearInterval(timer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [visible]);

  return (
    <div ref={ref} className={cn('overflow-hidden rounded-xl bg-zinc-950 p-4 text-sm leading-6 font-mono text-zinc-100 shadow-xl', className)}>
      <div className="mb-3 flex items-center gap-1.5 border-b border-zinc-700 pb-2">
        <span className="h-2.5 w-2.5 rounded-full bg-red-500" />
        <span className="h-2.5 w-2.5 rounded-full bg-amber-500" />
        <span className="h-2.5 w-2.5 rounded-full bg-green-500" />
        <span className="ml-2 text-xs text-zinc-500">Terminal</span>
      </div>
      <div className="grid gap-0.5 whitespace-pre-wrap">
        {lines.slice(0, revealed).map((line, i) => (
          <span
            key={i}
            className={
              line.startsWith('$')
                ? 'text-green-400'
                : line.startsWith('//') || line.startsWith('module') || line.startsWith('    ')
                  ? 'text-zinc-300'
                  : 'text-zinc-400'
            }
          >
            {line.startsWith('$ ') ? line : `  ${line}`}
          </span>
        ))}
        {revealed < lines.length && revealed > 0 && (
          <span className="inline-block h-4 w-2 animate-pulse bg-zinc-300" />
        )}
      </div>
    </div>
  );
}

export function RevealGroup({
  children,
  className,
  delay = 0,
}: {
  children: ReactNode;
  className?: string;
  delay?: number;
}) {
  const ref = useRef<HTMLDivElement>(null);
  const visible = useIsVisible(ref);
  const [show, setShow] = useState(false);

  useEffect(() => {
    if (!visible) return;
    const timer = setTimeout(() => setShow(true), delay);
    return () => clearTimeout(timer);
  }, [visible, delay]);

  return (
    <div
      ref={ref}
      className={cn(
        'transition-all duration-700',
        show ? 'translate-y-0 opacity-100' : 'translate-y-6 opacity-0',
        className,
      )}
    >
      {children}
    </div>
  );
}

/** SVG circuit trace decoration */
export function CircuitLines({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 200 200"
      className={cn('pointer-events-none text-green-800/20 dark:text-green-600/15', className)}
      fill="none"
      aria-hidden="true"
    >
      <path d="M0 40h40l10-20h50" stroke="currentColor" strokeWidth="1.5" />
      <circle cx="40" cy="40" r="2" fill="currentColor" />
      <path d="M200 160h-40l-10 20H90" stroke="currentColor" strokeWidth="1.5" />
      <circle cx="160" cy="160" r="2" fill="currentColor" />
      <path d="M100 0v30l10 10v40" stroke="currentColor" strokeWidth="1" />
      <path d="M40 200v-30l10-10V90" stroke="currentColor" strokeWidth="1" />
      <circle cx="100" cy="70" r="3" fill="currentColor" />
      <path d="M70 100h60" stroke="currentColor" strokeWidth="1" strokeDasharray="3 3" />
      <circle cx="70" cy="100" r="2" fill="currentColor" />
      <circle cx="130" cy="100" r="2" fill="currentColor" />
    </svg>
  );
}
